blood_moon:
  duration: 600 # In seconds
  enabled_worlds:
    - world
  bossbar:
    title: "Blood Moon"
    color: RED
  enemy_modifier:
    health: 2
    damage: 2
    speed: 1.5
  on_enemy_death:
    additional_drops:
    - "GOLD_INGOT:1"
  on_enemy_attack:
    bleeding: true
    effects:
    - SLOWNESS:2:0
    - NAUSEA:2:0
    - WEAKNESS:2:0
    sounds:
    - ENTITY_PLAYER_HURT

headless_horseman:
  duration: 600 # In seconds 
  enabled_worlds:
    - world
  bossbar:
    title: "Headless Horseman"
    color: PURPLE
  enemy_modifier:
    health: 2
    damage: 2
    speed: 1.5
  on_enemy_death:
    additional_drops:
    - "IRON_INGOT:1"
  on_enemy_attack:
    effects:
    - SLOWNESS:2:0
    - BBLINDNESS:2:0
    - WEAKNESS:2:0
    sounds:
    - ENTITY_PLAYER_HURT

# Only if UniversalNotifier is installed
# This is usefull to send notificaions via telegram, discord or email
# https://builtbybit.com/resources/universalnotifier-broadcast-alerts.62960/
notifier:
  blood_mone: "🩸 A blood moon is rising! The night will be long and full of terrors!"
  headless_horseman: "🏇 The headless horseman is coming! Prepare for battle!"

# Can be any time in the format of HH:MM
# The event will start at the time specified
scheduler:
  monday:
    "22:00": "BLOOD_MOON"
  tuesday:
    "22:00": "HEADLESS_HORSEMAN"w
  ednesday:
   "22:00": "BLOOD_MOON"
  thursday:
    "22:00": "HEADLESS_HORSEMAN"
  friday:
    "22:00": "BLOOD_MOON"
  saturday:
    "22:00": "HEADLESS_HORSEMAN"
  sunday:
    "22:00": "BLOOD_MOON"