blood_moon:
  duration: 10 # In minutes
  enabled_worlds:
    - world
  bossbar:
    title: "Blood Moon"
    color: RED
  enemy_modifier:
    health: 2
    damage: 2
    speed: 2
  on_enemy_death:
    additional_drops:
    - "GOLD_INGOT:1"
  on_enemy_attack:
    bleeding: true
    effects:
    - SLOWNESS:2:0
    - NAUSEA:2:0
    - WEAKNESS:2:0
    sounds:
    - ENTITY_PLAYER_HURT

headless_horseman:
  duration: 10 # In minutes 
  enabled_worlds:
    - world
  bossbar:
    title: "Headless Horseman"
    color: PURPLE
  enemy_modifier:
    health: 2
    damage: 2
    speed: 2
  on_enemy_death:
    additional_drops:
    - "IRON_INGOT:1"
  on_enemy_attack:
    effects:
    - SLOWNESS:2:0
    - BBLINDNESS:2:0
    - WEAKNESS:2:0
    sounds:
    - ENTITY_PLAYER_HURT


# Can be any time in the format of HH:MM
# The event will start at the time specified
scheduler:
  monday:
    "22:00": "BLOOD_MOON"
  tuesday:
    "22:00": "HEADLESS_HORSEMAN"
  ednesday:
   "22:00": "BLOOD_MOON"
  thursday:
    "22:00": "HEADLESS_HORSEMAN"
  friday:
    "22:00": "BLOOD_MOON"
  saturday:
    "22:00": "HEADLESS_HORSEMAN"
  sunday:
    "22:00": "BLOOD_MOON"